.TH "/home/jerome/projects/WeatherCheckingRpi/weathercheckingrpi Directory Reference" 3 "Mon Apr 15 2019" "WeatherCheckingRpi project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jerome/projects/WeatherCheckingRpi/weathercheckingrpi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBappmodel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBappmodel\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
