.TH "AppModelPrivate" 3 "Tue Apr 30 2019" "WeatherCheckingRpi project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppModelPrivate
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppModelPrivate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWeatherData\fP \fBnow\fP"
.br
.ti -1c
.RI "bool \fBready\fP"
.br
.ti -1c
.RI "QTimer \fBrequestNewWeatherTimer\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AppModelPrivate::AppModelPrivate ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBWeatherData\fP AppModelPrivate::now"

.SS "bool AppModelPrivate::ready"

.SS "QTimer AppModelPrivate::requestNewWeatherTimer"


.SH "Author"
.PP 
Generated automatically by Doxygen for WeatherCheckingRpi project from the source code\&.
