.TH "AppModel" 3 "Tue Apr 30 2019" "WeatherCheckingRpi project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppModel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <appmodel\&.h>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "Q_INVOKABLE void \fBrefreshWeather\fP ()"
.br
.RI "\fBAppModel::refreshWeather\fP Access http://api.openweathermap.org/data/2.5/weather site to get a specific city data Deals with connection errors\&. "
.ti -1c
.RI "void \fBmeasurevalue\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBreadyChanged\fP ()"
.br
.ti -1c
.RI "void \fBweatherChanged\fP ()"
.br
.ti -1c
.RI "void \fBmeasurementsUpdated\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppModel\fP (QObject *parent=nullptr)"
.br
.RI "[0] "
.ti -1c
.RI "\fB~AppModel\fP ()"
.br
.ti -1c
.RI "bool \fBhasValidWeather\fP () const"
.br
.ti -1c
.RI "bool \fBready\fP () const"
.br
.ti -1c
.RI "\fBWeatherData\fP * \fBweather\fP () const"
.br
.ti -1c
.RI "void \fBhandleZambrettiData\fP ()"
.br
.ti -1c
.RI "void \fBhandleZambrettiNum\fP (int)"
.br
.ti -1c
.RI "void \fBmanageMetricsAverage\fP (Zambretti *Zamb)"
.br
.ti -1c
.RI "QJsonDocument \fBbuildZambrettiQJsonDocument\fP (QString zpathtable)"
.br
.ti -1c
.RI "void \fBprintMeasurement\fP (struct data data) const"
.br
.ti -1c
.RI "void \fBprintMeasurements\fP () const"
.br
.ti -1c
.RI "void \fBsetZambrettiQJsonDocument\fP ()"
.br
.ti -1c
.RI "QJsonDocument \fBgetZtable\fP () const"
.br
.ti -1c
.RI "void \fBsetZtable\fP (const QJsonDocument &value)"
.br
.ti -1c
.RI "MetricsAverage \fBgetMeasurement\fP () const"
.br
.ti -1c
.RI "void \fBsetMeasurement\fP (const MetricsAverage &value)"
.br
.ti -1c
.RI "vector< struct data > \fBgetMeasurements\fP () const"
.br
.ti -1c
.RI "void \fBsetMeasurements\fP (const vector< struct data > &value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QJsonDocument \fBztable\fP"
.br
.ti -1c
.RI "MetricsAverage \fBmeasurement\fP"
.br
.ti -1c
.RI "vector< struct data > \fBmeasurements\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBready\fP"
.br
.ti -1c
.RI "\fBWeatherData\fP \fBweather\fP"
.br
.ti -1c
.RI "bool \fBhasValidWeather\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AppModel::AppModel (QObject * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
[0] 
.SS "AppModel::~AppModel ()"

.SH "Member Function Documentation"
.PP 
.SS "QJsonDocument AppModel::buildZambrettiQJsonDocument (QString zpathtable)"

.SS "MetricsAverage AppModel::getMeasurement () const"

.SS "vector< struct data > AppModel::getMeasurements () const"

.SS "QJsonDocument AppModel::getZtable () const"

.SS "void AppModel::handleZambrettiData ()"

.SS "void AppModel::handleZambrettiNum (int)"

.SS "bool AppModel::hasValidWeather () const"

.SS "void AppModel::manageMetricsAverage (Zambretti * Zamb)"

.SS "void AppModel::measurementsUpdated ()\fC [signal]\fP"

.SS "void AppModel::measurevalue ()\fC [slot]\fP"
call MetricsAverage mesurevalue method add metrics data to \fBAppModel\fP measurements vector 
.SS "void AppModel::printMeasurement (struct data data) const"

.SS "void AppModel::printMeasurements () const"

.SS "bool AppModel::ready () const"

.SS "void AppModel::readyChanged ()\fC [signal]\fP"

.SS "void AppModel::refreshWeather ()\fC [slot]\fP"

.PP
\fBAppModel::refreshWeather\fP Access http://api.openweathermap.org/data/2.5/weather site to get a specific city data Deals with connection errors\&. 
.SS "void AppModel::setMeasurement (const MetricsAverage & value)"

.SS "void AppModel::setMeasurements (const vector< struct data > & value)"

.SS "void AppModel::setZambrettiQJsonDocument ()"

.SS "void AppModel::setZtable (const QJsonDocument & value)"

.SS "\fBWeatherData\fP* AppModel::weather () const"

.SS "void AppModel::weatherChanged ()\fC [signal]\fP"

.SH "Member Data Documentation"
.PP 
.SS "MetricsAverage AppModel::measurement"

.SS "vector<struct data> AppModel::measurements"

.SS "QJsonDocument AppModel::ztable"

.SH "Property Documentation"
.PP 
.SS "bool AppModel::hasValidWeather\fC [read]\fP"

.SS "bool AppModel::ready\fC [read]\fP"

.SS "\fBWeatherData\fP * AppModel::weather\fC [read]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for WeatherCheckingRpi project from the source code\&.
