.TH "/home/jerome/projects/WeatherCheckingRpi/weathercheckingrpi/appmodel.h" 3 "Mon Apr 15 2019" "WeatherCheckingRpi project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jerome/projects/WeatherCheckingRpi/weathercheckingrpi/appmodel.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtCore/QObject>\fP
.br
\fC#include <QtCore/QString>\fP
.br
\fC#include <QtNetwork/QNetworkReply>\fP
.br
\fC#include <QtQml/QQmlListProperty>\fP
.br
\fC#include <QtPositioning/QGeoPositionInfoSource>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWeatherData\fP"
.br
.RI "[0] "
.ti -1c
.RI "class \fBAppModel\fP"
.br
.RI "[2] "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WeatherCheckingRpi project from the source code\&.
