.TH "/home/jerome/projects/WeatherCheckingRpi/weathercheckingrpi/main.cpp" 3 "Tue Apr 30 2019" "WeatherCheckingRpi project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jerome/projects/WeatherCheckingRpi/weathercheckingrpi/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui/QGuiApplication>\fP
.br
\fC#include <QtQuick/QQuickView>\fP
.br
\fC#include <QtQml/QQmlEngine>\fP
.br
\fC#include <QtQml/QQmlContext>\fP
.br
\fC#include <QtQuick/QQuickItem>\fP
.br
\fC#include <QLoggingCategory>\fP
.br
\fC#include 'appmodel\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for WeatherCheckingRpi project from the source code\&.
